"""initial schema

Revision ID: b3aabaadbb1e
Revises: 
Create Date: 2026-10-06 10:42:44.185943
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b3aabaadbb1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='applicationstatus', native_enum=False), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_applications_slug'), 'applications', ['slug'], unique=True)
    op.create_table('datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'slug', name='uq_dataset_app_slug')
    )
    op.create_index(op.f('ix_datasets_application_id'), 'datasets', ['application_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_types', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='analysisstatus', native_enum=False), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('ai_interpretation', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_runs_app_created', 'analysis_runs', ['application_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_analysis_runs_application_id'), 'analysis_runs', ['application_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_dataset_id'), 'analysis_runs', ['dataset_id'], unique=False)
    op.create_table('dataset_fields',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('technical_type', sa.Enum('string', 'integer', 'float', 'boolean', 'date', 'datetime', name='datasetfieldtype', native_enum=False), nullable=False),
    sa.Column('semantic_type', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'name', name='uq_field_dataset_name')
    )
    op.create_index(op.f('ix_dataset_fields_dataset_id'), 'dataset_fields', ['dataset_id'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('trend', 'anomaly', 'risk', 'forecast', 'opportunity', 'recommendation', name='insighttype', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='insightseverity', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metric', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_analysis_run_id'), 'insights', ['analysis_run_id'], unique=False)
    op.create_index('ix_insights_run', 'insights', ['analysis_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_insights_run', table_name='insights')
    op.drop_index(op.f('ix_insights_analysis_run_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_dataset_fields_dataset_id'), table_name='dataset_fields')
    op.drop_table('dataset_fields')
    op.drop_index(op.f('ix_analysis_runs_dataset_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_application_id'), table_name='analysis_runs')
    op.drop_index('ix_analysis_runs_app_created', table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_datasets_application_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_applications_slug'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
